project:
  type: website
  output-dir: docs
website:
  google-analytics: "UA-XXXXXXXX"
  title: "Mauricio Patón"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: Mauricio-CV.qmd
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/
        
  page-footer:
    center: |
      [Contact me](mailto:maupagas@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org)
    right: |
      [Github Code Repo](https://github.com/mauricio-online-portfolio)
    background: "grey"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    code-link: true
    code-fold: show
    # code-tools: true
    highlight-style: github
    
