---
title: CV
format:
  html
author: Mauricio Patón Gassó, PhD
date: last-modified
phone: +971 50 649 4803
address: "Yas Island, Abu Dhabi (United Arab Emirates)"
email: maupagas@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
github: maupagas # github account
orcid: 0000-0002-1869-4448 # orcid identifier
scholar: https://scholar.google.com/citations?hl=en&user=qZJFgdwAAAAJ
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
linkedin: mauriciopaton # linkedin account
# web: https://maupagas.github.io/ # personal website
fontawesome: yes
nocite: '@*'
# bibliography: 
#   peer: peer_bib.bib
#   other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
---

# Summary

Researcher with **9+ years of experience** in the development of mathematical models (ranging from differential equations to machine-learning models) in the fields of environmental biotechnology and public health epidemiology. Passionate about creating models that inform decision-making and address real-world challenges.

--- 

# Employment

## **Postdoctoral Researcher at Khalifa University \hfill 2019-today** 

### COVID-19 Policy Insights: 

- Developed custom models for the **Department of Health of Abu Dhabi** that were used for policy decision-making during the pandemic, including:
  - An online simulation tool (deployed in **R and Shiny**) to simulate the spread of COVID-19 and assess [the effectiveness of potential interventions](https://envbioprom.shinyapps.io/COVID19_Model_KU/).
  - A model that evaluated [vaccine distribution strategies across different age groups](https://doi.org/10.1016/j.idm.2023.07.012) to minimize fatalities.

- Simulated for the **Expo 2020 organizers** the impact of international visitors on large-scale events to gain insights on how to [balance infection rates and economic impact](https://doi.org/10.1016/j.idm.2022.08.003). 

- **Performed ETL** on COVID-19 data sourced from the DOH. This involved **curating and consolidating** data, and **automating** the process to ensure accurate case reporting and **estimate model parameters**.

- Delivered to DOH stakeholders periodic automated **COVID-19 risk assessment reports** using **R and RMarkdown** (i.e. evaluation of the hospitalization risk associated with different SARS-CoV-2 variants).

### Secured University Funding:

- Successfully developed and implemented research proposals worth **1.3 million AED** in funding from the Department of Health (DOH) to Khalifa University. 

### Wastewater Treatment Modelling:

- Developed a customized [online simulation dashboard](https://envbioprom.shinyapps.io/bioreactor-dashboard/) for [ENEC](https://www.enec.gov.ae/) using Python to **evaluate the effectiveness and costs (CAPEX/OPEX)** of the proposed wastewater treatment system. 

## **PhD Candidate at Masdar Institute - Khalifa University \hfill 2015-19**

### Systematic Methodology for the Evaluation of Metabolic Pathways:
  
- Developed a **novel method** to compute energy yields of all combinations for specific metabolic pathways. This can be used to **inform the design** of bioprocess systems (i.e. set conditions to increase a product yield).

### Model Improvement in Bioreactor Simulations: 

- Enhanced an existing software in MATLAB and in Python to integrate the dynamic calculation of the bioenergetics of microbial reactions, resulting in an **estimated 5% improvement** of model predictions.

## **Intern Bioprocess Engineer at Paques BV (The Netherlands) \hfill 2014**

- Operated a small-scale bioreactor and conducted lab sample measurements for a wastewater treatment project at a bioethanol production plant from [_St1 Nordic_](https://www.st1.com/)  (Finland). This work eventually resulted in the successful installation of a **€5 million bioreactor** at the client's facility in 2015.

--- 

# Education

**PhD in Interdisciplinary Engineering - Khalifa University (UAE)  \hfill 2015-19 **\newline
Thesis: “Bioenergetics analyses of microbial reactions for anaerobic digestion modelling”

**MSc in Hydraulic Engineering and Environment - Polytechnic University of Valencia (Spain)  \hfill 2010-12**   \newline
Thesis: “Modelling anaerobic digestion process of a pilot plant treating bioethanol plant wastewater”

**BSc in Environmental Sciences - Polytechnic University of Valencia (Spain)  \hfill 2004-10** \newline
Thesis:  “Modeling anaerobic digestion process of sludge from WWTP. Influence of the sludge composition on biogas production”

--- 

# Other Education

• HarvardX Data Science Professional Certificate Program - [Certificate](https://credentials.edx.org/credentials/d1e970d9bb5c428ebfc4826df5410c1c/) \
• Complete Course of Machine Learning: Data Science with R Studio (Udemy) - [Certificate](https://udemy-certificate.s3.amazonaws.com/pdf/UC-a0b88b8f-a4a3-449b-ab3d-78bd66b1ce56.pdf) \
• DeepLearning.ai Machine Learning Specialization - [Certificate](https://coursera.org/verify/specialization/4W9PK2FVM9WE) \
• DeepLearning.ai Neural Networks and Deep Learning – [Certificate](https://www.coursera.org/account/accomplishments/verify/NA95VMDG7ZWX) \
• DeepLearning.ai TensorFlow Developer – [Certificate](https://www.coursera.org/account/accomplishments/specialization/certificate/TVZCM9FRKGQL) \

---

**Skills:** Python, R, MATLAB, SQL, Tensorflow, Git. \
**Languages:** Spanish (native), English (Proficient), Catalan (native).